# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62fa4b064627377ddb508fb593b159b6433075aade1c729530d31ca99ee940736a1e1c5bd506434c69cfee2b1ae58af00d19a2612d54c1dfb9974fe258ebd885

test:
  secret_key_base: 3ffd93d2374d20f37318982a6676d8e6fdb44dbffa2e2bd161391c5b27846f1526b483fd71225c0056fa92a91ceb1df5ad2e7188260b69bf72945d6095264904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
